

platform :ios, "8.0"
target 'WTChatDemo'



pod 'MJRefresh',                '~> 3.1.12'
pod 'FDFullscreenPopGesture',   '~> 1.1'
pod 'IQKeyboardManager',        '~> 4.0.2'
pod 'YYModel',                  '~> 1.0.3'
pod 'YYWebImage',               '~> 1.0.3'
